new version README template
WordPress/block-development-examples pull request #49
Opened 2023-11-07 11:13 UTC by juanmaguitar

UPDATE template for individual READMEs
This version simplifies the instructions and put at the same level the two main use cases to check the examples locally:
- as part of the monorepo
- as part of the user's own WordPress installation

If approved, we'd need to update the individual READMEs using this template

2023-11-07 15:20 UTC, ryanwelcher requested changes
Some minor changes in the readme. Do we also need to move this into the readme that is [part of the template?](https://github.com/wptrainingteam/block-development-examples/blob/trunk/templates/block-examples/templates/plugin/README.md.mustache)

2023-11-07 15:20 UTC, ryanwelcher commented on templates/block-examples/readmes/README-EXAMPLE.tpl.md
> +3. Use it in a WordPress
```suggestion
3. Use it in a WordPress installation
```

2023-11-07 15:20 UTC, ryanwelcher commented on templates/block-examples/readmes/README-EXAMPLE.tpl.md
> +3. Use it in a WordPress
I think we're missing a word.

2023-11-07 15:20 UTC, ryanwelcher commented on templates/block-examples/readmes/README-EXAMPLE.tpl.md
> +The quickest way to have access to all the examples is clone this repository and check the examples locally.
```suggestion
The quickest way to have access to all the examples is clone this repository and check out the examples locally.
```

2023-11-07 15:20 UTC, ryanwelcher commented on templates/block-examples/readmes/README-EXAMPLE.tpl.md
> +Once the depencies are installed (a `node_modules` folder should have been created), [launch the build process](https://github.com/wptrainingteam/block-development-examples/wiki/05-Development#build-
```suggestion
Once the depencies are installed (a `node_modules` folder should have been created), [launch the build process](https://github.com/wptrainingteam/block-development-examples/wiki/05-Development#build-process) to get the final version of the block that can be used in WordPress. 
```

2023-11-07 15:20 UTC, ryanwelcher commented on templates/block-examples/readmes/README-EXAMPLE.tpl.md
> +If you have a local WordPress installation already running, you can also put the plugin folders of the examples you're interested in (by copyin and paste, from the zips...) inside the `plugins` folde
```suggestion
If you have a local WordPress installation already running, you can also put the plugin folders of the examples you're interested in (by copying and pasting, from the zips...) inside the `plugins` folder of that installation and check the examples there.
```

2023-11-08 17:18 UTC, juanmaguitar commented
@ryanwelcher suggestions accepted 👍

> Do we also need to move this into the readme that is [part of the template?](https://github.com/wptrainingteam/block-development-examples/blob/trunk/templates/block-examples/templates/plugin/README.md.mustache)

Yes! We would need to update all the individual readme's and the template

2023-11-08 20:34 UTC, ryanwelcher approved these changes
Looks good to me. Do we want to tackle the tempate/existing readme files in a separate PR?

2023-11-09 18:37 UTC, merged

2023-11-09 18:37 UTC, juanmaguitar commented
> Looks good to me. Do we want to tackle the tempate/existing readme files in a separate PR?

Yes, I'll open a separate PR for those changes